# Generated by Django 6.0.1 on 2026-01-28 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jefesubprograma',
            name='sub_programa',
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('rol', models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('JEFE_SUB_PROGRAMA', 'Jefe de Sub Programa')], default='ESTUDIANTE', max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='personas/')),
                ('sub_programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personas', to='registros.subprograma')),
            ],
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.DeleteModel(
            name='JefeSubPrograma',
        ),
    ]
