# Generated by Django 6.0.1 on 2026-02-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_persona_password_persona_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name=models.EmailField(blank=True, max_length=255, null=True)),
            preserve_default=False,
        ),
    ]
