# Generated by Django 6.0.1 on 2026-01-28 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registros', '0003_persona_password_persona_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('rol', models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('JEFE_SUB_PROGRAMA', 'Jefe de Sub Programa')], default='ESTUDIANTE', max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='preregistro/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('sub_programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preregistros', to='registros.subprograma')),
            ],
        ),
    ]
