# Generated by Django 6.0.1 on 2026-01-28 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preregistro',
            name='aprobado',
        ),
    ]
