# Generated by Django 6.0.1 on 2026-02-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0002_remove_preregistro_aprobado'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistro',
            name='email',
            field=models.EmailField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
