# Generated by Django 6.0.1 on 2026-01-28 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registros', '0003_persona_password_persona_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_incidencia', models.CharField(choices=[('INSCRIPCION_TEMPORAL', 'Inscripción Temporal'), ('REINGRESO', 'Reingreso'), ('CARGA_NOTAS_TEMPORAL', 'Carga de Notas Temporal'), ('AUTO_ESTUDIO', 'Auto Estudio'), ('PRUEBA_GLOBAL', 'Prueba Global'), ('DENUNCIA', 'Denuncia'), ('INTERSEMESTRAL', 'Solicitud de Intersemestral')], max_length=30)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='registros.persona')),
            ],
        ),
        migrations.CreateModel(
            name='IncidenciaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Solo imágenes en formato JPEG', upload_to='incidencias/')),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='incidencias.incidencia')),
            ],
        ),
    ]
