# Generated by Django 6.0.1 on 2026-01-28 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0001_initial'),
        ('registros', '0003_persona_password_persona_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='estado',
            field=models.CharField(choices=[('CREADA', 'Creada'), ('ABIERTA', 'Abierta'), ('RESUELTA', 'Resuelta'), ('RECHAZADA', 'Rechazada')], default='CREADA', max_length=10),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('es_admin', models.BooleanField(default=False)),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='incidencias.incidencia')),
                ('remitente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_enviados', to='registros.persona')),
            ],
            options={
                'ordering': ['fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='MensajeImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Solo imágenes en formato JPEG o PNG', upload_to='mensajes/')),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='incidencias.mensaje')),
            ],
        ),
    ]
