# Generated by Django 6.0.1 on 2026-01-28 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0002_incidencia_estado_incidencia_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='es_admin',
        ),
    ]
