# Generated by Django 6.0.1 on 2026-01-28 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0003_remove_mensaje_es_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensaje',
            options={},
        ),
        migrations.RenameField(
            model_name='mensaje',
            old_name='fecha_envio',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='remitente',
        ),
        migrations.AlterField(
            model_name='incidenciaimagen',
            name='imagen',
            field=models.ImageField(upload_to='incidencias/'),
        ),
        migrations.AlterField(
            model_name='mensajeimagen',
            name='imagen',
            field=models.ImageField(upload_to='mensajes/'),
        ),
    ]
