# Generated by Django 6.0.1 on 2026-02-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0004_alter_mensaje_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='leido_por_estudiante',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='leido_por_jefe',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='autor_ci',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
